//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerebro14.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABacciones
    {
        public int id { get; set; }
        public int tipo { get; set; }
        public string parametros { get; set; }
        public double FK_Eve_Lat { get; set; }
        public double FK_Eve_Lon { get; set; }
        public string FK_email_usu { get; set; }
    
        public virtual TABeventos TABeventos { get; set; }
        public virtual TABusuarios TABusuarios { get; set; }
    }
}
