//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerebro14.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABacciones
    {
        public int id { get; set; }
        public int tipo { get; set; }
        public string parametros { get; set; }
        public double FK_Eve_Lat { get; set; }
        public double FK_Eve_Lon { get; set; }
        public string FK_email_usu { get; set; }
    
        public virtual TABeventos TABeventos { get; set; }
        public virtual TABusuarios TABusuarios { get; set; }
    }
}
