//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerebro14.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABCiudades
    {
        public double RecursoLibre { get; set; }
        public double ID_Ciu_Lat { get; set; }
        public double ID_Ciu_Lon { get; set; }
        public string NameDbSQL { get; set; }
        public string UserDb { get; set; }
        public string PassDb { get; set; }
        public string NameDbM { get; set; }
        public string AddressServerDb { get; set; }
        public double PortServerDb { get; set; }
        public string NameCiudade { get; set; }
        public int id { get; set; }
    }
}
