//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerebro14.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABCiudades
    {
        public double RecursoLibre { get; set; }
        public double ID_Ciu_Lat { get; set; }
        public double ID_Ciu_Lon { get; set; }
        public string NameDbSQL { get; set; }
        public string UserDb { get; set; }
        public string PassDb { get; set; }
        public string NameDbM { get; set; }
        public string AddressServerDb { get; set; }
        public double PortServerDb { get; set; }
        public string NameCiudade { get; set; }
        public int id { get; set; }
    }
}
