//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerebro14.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABeventoTipo
    {
        public int id { get; set; }
        public double FK_EvetoT_Lat { get; set; }
        public double FK_EvetoT_Lon { get; set; }
        public double umbral { get; set; }
        public string FK_tipo { get; set; }
    }
}
