//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerebro14.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABsensorEvento
    {
        public int id { get; set; }
        public double umbral { get; set; }
        public double FK_Sensor_Lat { get; set; }
        public double FK_Sensor_Lon { get; set; }
        public double FK_Eveto_Lat { get; set; }
        public double FK_Eveto_Lon { get; set; }
    
        public virtual TABeventos TABeventos { get; set; }
        public virtual TABsensor TABsensor { get; set; }
    }
}
