//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerebro14.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABZona
    {
        public int id { get; set; }
        public double Lat_Zona { get; set; }
        public double Lon_Zona { get; set; }
        public double Radio_Zona { get; set; }
        public string Name_Zona { get; set; }
        public string Zona_string_extra { get; set; }
        public Nullable<double> Zona_num_extra { get; set; }
    }
}
